name: Build

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 20
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
      - name: Install dependencies
        run: |
          pacman --sync --noconfirm --needed \
            make mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake
          pacman --sync --noconfirm --needed \
            mingw-w64-x86_64-libjpeg-turbo \
            mingw-w64-x86_64-gnutls mingw-w64-x86_64-pixman \
            mingw-w64-x86_64-nettle mingw-w64-x86_64-gmp
          # MSYS2 only packages FLTK 1.4 now:
          # https://github.com/msys2/MINGW-packages/issues/22769
          pacman --upgrade --noconfirm --needed \
            https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-fltk-1.3.9-2-any.pkg.tar.zst
      - name: Configure
        run: cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Debug -S . -B build
      - name: Build
        run: cmake --build build
      - name: Install
        env:
          MSYS2_PATH_TYPE: inherit
        run: cmake --build build installer winvnc_installer
      - uses: actions/upload-artifact@v4
        with:
          name: Windows
          path: build/release/tigervnc*.exe
