name: Build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        static: ["ON", "OFF"]
      fail-fast: false
    name: Linux (static ${{ matrix.static }})
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfltk1.3-dev fluid gettext appstream
          sudo apt-get install -y libgnutls28-dev nettle-dev libgmp-dev
          sudo apt-get install -y libxtst-dev libxdamage-dev libxfixes-dev libxrandr-dev libpam-dev
          sudo apt-get install -y libavcodec-dev libavutil-dev libswscale-dev
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_STATIC=${{ matrix.static }} -S . -B build
      - name: Build
        working-directory: build
        run: make
      - name: Install
        working-directory: build
        run: make tarball
      - name: Failure build logs
        if: ${{ failure() }}
        run: |
          pwd
          for log in build/CMakeFiles/*.log; do
            echo
            echo @@@@@@@@@@@@@@@@ ${log} @@@@@@@@@@@@@@@@
            echo
            cat ${log}
          done
      - uses: actions/upload-artifact@v3
        with:
          name: Linux (Ubuntu)
          path: build/tigervnc-*.tar.gz

  build-windows:
    runs-on: windows-latest
    timeout-minutes: 20
    strategy:
      matrix:
        static: ["ON", "OFF"]
      fail-fast: false
    name: Windows (static ${{ matrix.static }})
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
      - name: Install dependencies
        run: |
          pacman --sync --noconfirm --needed \
            make mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake
          pacman --sync --noconfirm --needed \
            mingw-w64-x86_64-fltk mingw-w64-x86_64-libjpeg-turbo \
            mingw-w64-x86_64-gnutls mingw-w64-x86_64-pixman \
            mingw-w64-x86_64-nettle mingw-w64-x86_64-gmp
      - name: Configure
        run: cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Debug -DBUILD_STATIC=${{ matrix.static }} -S . -B build
      - name: Build
        working-directory: build
        run: make
      - name: Install
        working-directory: build
        env:
          MSYS2_PATH_TYPE: inherit
        run: make installer winvnc_installer
      - name: Failure build logs
        if: ${{ failure() }}
        run: |
          for log in build/CMakeFiles/*.log; do
            echo
            echo @@@@@@@@@@@@@@@@ ${log} @@@@@@@@@@@@@@@@
            echo
            cat ${log}
          done
      - uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: build/release/tigervnc*.exe

  build-macos:
    runs-on: macos-latest
    timeout-minutes: 20
    strategy:
      matrix:
        static: ["ON", "OFF"]
      fail-fast: false
    name: macOS (static ${{ matrix.static }})
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          brew install fltk pixman ffmpeg
          brew install gnutls nettle gmp
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_STATIC=${{ matrix.static }} -S . -B build
      - name: Build
        working-directory: build
        run: make
      - name: Install
        working-directory: build
        run: make dmg
      - name: Failure build logs
        if: ${{ failure() }}
        run: |
          for log in build/CMakeFiles/*.log; do
            echo
            echo @@@@@@@@@@@@@@@@ ${log} @@@@@@@@@@@@@@@@
            echo
            cat ${log}
          done
      - uses: actions/upload-artifact@v3
        with:
          name: macOS
          path: build/TigerVNC-*.dmg

  build-java:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        java: [ '8', '11', '16' ]
    name: Java (version ${{ matrix.java }})
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Configure
        working-directory: java
        run: cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build
      - name: Build
        working-directory: java/build
        run: make
      - name: Failure build logs
        if: ${{ failure() }}
        run: |
          for log in java/build/CMakeFiles/*.log; do
            echo
            echo @@@@@@@@@@@@@@@@ ${log} @@@@@@@@@@@@@@@@
            echo
            cat ${log}
          done
      - uses: actions/upload-artifact@v3
        with:
          name: Java (${{ matrix.java }})
          path: java/build/VncViewer.jar

  build-packages:
    timeout-minutes: 20
    strategy:
      matrix:
        target:
          - centos7
          - rocky8
          - rocky9
          - bionic
          - focal
          - jammy
      fail-fast: false
    name: Linux packages (${{ matrix.target }})
    runs-on: ubuntu-latest
    env:
      DOCKER: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t tigervnc/$DOCKER .github/containers/$DOCKER
      - name: Build packages
        run: .github/containers/$DOCKER/build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: Packages (${{ matrix.target }})
          path: .github/containers/${{ matrix.target }}/result
